### ISSUE TITLE
Hypha Token Redistribution (M)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dao-contracts#168]
## Spec [Draft - not ready]

It will have a table with new values for people, based on the spreadsheet. 

https://docs.google.com/spreadsheets/d/1e6ic2M3vtH4DFUQGSvGxzB2QSUTntMsE8ApdB_RDmOU/edit?usp=sharing

(add IPFS link here also)

On execution, it redistributes the tokens as per the table, then sends them all to the liquidity vesting contract
(see https://github.com/hypha-dao/dao-contracts/issues/173)

### Options - see below 

# Execution Steps

More or less in order - check off as they're done.

- [x] Audit the vesting / collective sales contract (CS)
- [x] Run the unit tests on CS contract
- [x] create costake.hypha contract (@dappdever , add dao.hypha to permissions for "hypha")
- [x] Add permissions for Nik to vest.hypha (@dappdever dev key, account, whatever)
- [x] Deploy CS contract to vest.hypha (Nik)
- [x] Create reduce action on token.hypha (Nik)
- [x] Test reduce action on token.hypha (Nik)
- [x] Create permissions allowing dao.hypha to call createlock on CS contract
- [x] Create msig to reduce everyone's accounts, then add locks for everyone, then add the total sum to the lock contract (90% done)
- [x] deploy token.hypha
- [x] Code change on dao.hypha to pause payouts
- [x] **pause payouts** Deploy dao.hypha
- [x] add HYPHA token to costak.hypha allowed tokens
- [x] Test the entire sequence on local net - delete balance, add lock
- [x] Update the Hypha token balances in the spreadsheet
- [x] Export the Hypha token balances to csv as basis for the actions
- [x] Run actions on everyone's accounts to remove their Hypha, add balance in costak.hypha contract
- [x] Change token price to 0.50 USD
- [x] Change dao.hypha payouts so they create locks on vest.hypha instead of liquid payouts
- [x] **Unpause payouts**
- [x] Do voice reset => see  #167

Doesn't need to have migrate code, or a table with values that needs to be filled
Doesn't need special permissions

It's going to just be a series of actions that can be executed by dao.hypha permissions

# Implementation Option A

Migrate Action on dao.hypha: Reduces balance and creates vesting lock, issues vesting token to vesting contract
params: account
signed by: account

1 - Pause payouts
2 - deploy vesting contract
3 - fill vesting migration table (balance in / out), using my script.
4 - change token price to 1.53 USD
5 - deploy new token with reduce action
6 - deploy DAO with migrate action
7 - Unpause payouts

The trick here, and reason it works like this, is that people can then have 90 days to move their balance, but ongoing payouts don't cause problems, since the in/out values are fixed in time in the migration table

Around 1-2 extra day compared to the simple "we just move everyone over" approach, since I need to add a migration table to the vesting contract, and the code in "migrate" action.

# Implementation Option B
1- freeze payouts on contract and website
2 - deploy updated token and voice token contracts, deploy vesting (aka collective sales) contract. Maybe also dao.hypha (depending on how we do the redistribution, talking about this with Max).
3 - Make msig transactions for the redistribution
4 - change the HYPHA price to 1.53 USD (from 8)
5 - Make HYPHA payments go into collective sales (vesting) contract instead of paying out in liquid tokens
5 - unfreeze 

Pro: Easier than A
Con: No user interaction or user choice to migrate

**Comment by n13** [comment]
- Change balances
- Move to escrow
- Show total in escrow? 
- Change price to 1.3
- Future payouts go to vesting contract

**Comment by n13** [comment]
Alternative - just do it all for people

More or less in order - check off as they're done.

- [ ] Audit the vesting / collective sales contract (CS)
- [ ] Run the unit tests on CS contract
- [ ] create vest.hypha contract (@dappdever , add dao.hypha to permissions for "hypha")
- [ ] Add permissions for Nik to vest.hypha (@dappdever dev key, account, whatever)
- [ ] Deploy CS contract to vest.hypha (Nik)
- [ ] Create reduce action on token.hypha (Nik)
- [ ] Create permissions allowing dao.hypha to call createlock on CS contract
- [ ] Create msig to reduce everyone's accounts, then add locks for everyone, then add the total sum to the lock contract (90% done)
- [ ] deploy token.hypha
- [ ] Pause payouts
- [ ] Change token price to 1.53 USD
- [ ] Change dao.hypha payouts so they create locks on vest.hypha instead of liquid payouts
- [ ] Unpause payouts
- [ ] Do voice reset => see  #167


Doesn't need to have migrate code, or a table with values that needs to be filled
Doesn't need special permissions

It's going to just be a series of actions that can be executed by dao.hypha permissions
