### ISSUE TITLE
Phone Number for Testnet [S]

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dao-contracts#171]
**Summary:**
As a DHO user I would like to be able to have a "fake phone number" / "fake verification code" that can be used to test registration on the test DHO:  https://dao-dev.hypha.earth/#/dashboard

Acceptance Criteria:

- [ ] have a verification code that always works for testnet

**Comment by dappdever** [comment]
We are working on fixing a dependent issue to this one, and that is one is now close to resolution. 

While I was testing the SMS registration services, I didn't use a fake number (because we want the SMS to actually send for some tests). Instead, I created a service for `delete` number from the table. This will allow a tester to use their same number over and over, as long as they call `delete` in between. I think this is best because it allows testing the full scenario. The downside is that each SMS does have a cost, so we wouldn't want to automate it, but it is fine for manual testing. 

I hard-coded the hash of my phone number in the source code. We could either just add hashes to the source code for other testers we want to allow, or move it to an environment variable or other configuration. Either is fine.

The actions to implement this are:

- [ ] Update the conditionals for which hashes of SMS numbers to allow to delete from a single number to a list of them: https://gitlab.com/telos-kitchen/telos-account-creator-services/-/blob/master/util.js#L66
- [ ] Calculate the hashes of the phone numbers who should have this authority. Note on line 62, there is a function call to `cleanNumberFormat`. This function converts the phone number to a canonical format which may be different than the one you key in. That is the value that gets hashed though, so you need to confirm what that is for your number. I recommend running the code and logging it to see it for that number. (this is also the function that blocks voip numbers): https://gitlab.com/telos-kitchen/telos-account-creator-services/-/blob/master/libs/send-lib.js#L13
- [ ] Add a feature to the client that enables deleting a number. This should only be visible in test.

**Comment by sebastianmontero** [comment]
@dappdever, @leonieherma1, @dappdever who needs to be added to the list that has the authority to delete their phone number?
Also, do we need a frontend UI for this? Or having the api call available to be called with something like curl be enough?

**Comment by dappdever** [comment]
> @dappdever, @leonieherma1, @dappdever who needs to be added to the list that has the authority to delete their phone number? Also, do we need a frontend UI for this? Or having the api call available to be called with something like curl be enough?

@sebastianmontero for the API call, are you referring to adding a telephone number to the authorized list?  If so, that is fine. I don't see it changing much.  @leonieherma1 Can you help put together the list of phone numbers?  They should privately DM'd to either me or Sebastian and we can add it.

**Comment by sebastianmontero** [comment]
@dappdever by the API call I meant the one to delete the record, do we need a UI for this?

**Comment by sebastianmontero** [comment]
@dappdever  It could just be called using something like curl or postman

**Comment by sebastianmontero** [comment]
Users with whitelisted numbers can run the following to delete their record:
`curl --location --request POST 'https://opqeierg9e.execute-api.us-east-1.amazonaws.com/dev/delete' \
--header 'x-api-key: 6jPyLJzRUwanRseq8vyGw68FdupCZhXy4PcPQkY1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "smsNumber": "<Replace with phone number>"
}'`

**Comment by leonieherma1** [comment]
@juliolrmonteiro @sceenius 

https://dao-dev.hypha.earth/#/preview/login
