### ISSUE TITLE
Create magic invite link to DAO 

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dao-contracts#312]
Summary:
As a DAO creator I want to be able to invite admins to my new DAO.

AC:
- [ ] generate link based on title of DAO

**Comment by arsenijesavic** [comment]
@leonieherma1 @n13 ^^

**Comment by n13** [comment]
> What is the flow expected for this?
> 
> I.e. 1.- Admin push button to generate link (calls action) 1.1.- Is this link only valid for X account or anyone could use it? And after is used once it's no longer valid? 2.- Client Query for generated link 3.- Admin copy link and sends to user ? 4.- Where is the link going to point? Dao login? Another Page where it will call a claim action so backend can validate the link 5. If links is valid what would happen? Auto enrroll user to dao as a member? Admin?

We have talked about two ways of doing this

We will do (1) right now

1 - We create a link to the DAO. 

Once the user gets to that link - a normal web link to the DAO, like here the MoM DAO:

https://dao.hypha.earth/momdho/login

Then they log in or sign up using the normal flow. 

We said that's what we do for now, because it's easiest. No work on the backend at all. Just link to the DAO. I am not sure how the URL is generated - is that just the DAO name, or is that something the DAO can do in settings?

Either way, that's all we do for option (1). 

2 - Send out invite links that onboard people. 

We are not ready for this because we don't yet have a good idea how we do this with Anchor mobile app

We also don't have our own mobile app which could do this. 

The system would be the same as the Seeds onboarding contract. I was thinking I would make it more generic and allow anyone to become a sponsor of invites so the system could be used by all of EOS / Telos. 

But that aside it always has to do with a secret. 

1 - I generate a secret on my local app, then hash this secret and create an invite on-chain that has the secret and I also send the token balance I need to send to make this happen.

2 - I send a magic link with the secret to someone, and they get onboarded very easily into Hypha - this requires an app. 

3 - User receives link (as message, email, whatever channel they used), user gets directed to download the app if they don't have it. 

Then the app opens with the link, or on first open if they downloaded it, they see a screen where they enter their real name. 

Then they see a screen which has their Telos/EOS username pre-filled, based on their real name, e.g. nikheger1111 - we just generate a name from the real name, filling it up to 12 characters if needed, shortening if needed, removing spaces etc. We also make sure that the account is available. User doesn't do anything - all they have to do is hit next, and they're in. 

They are prompted to save the key later. 

So there's only one step to create an EOSIO account, which is to enter your real name. 

I think that's the easiest onboarding possible into EOSIO and the easiest out there. 

Works well too, I've observed people out in the wild onboarding many times. No problems. Some had problems when they started editing their auto-generated name, then they get into the whole issue with all the EOSIO name limitations, but we do that the same way Hypha website does it, it slways shows which rules are not satisfied (e.g. must be 12 characters, etc)
